# This script extracts headword, POS, frequency, and attested spellings
# from the Dictionary of Old English A--H CD-ROM (if HTML at ./doe/).
# Copyright Paul Langeslag 2026
# TODO: readd epigraphy and other allcaps forms, which are filtered out at re.search()
# TODO: consider cutting fragmentary readings
import json,re,argparse
from pathlib import Path
from bs4 import BeautifulSoup

argparser = argparse.ArgumentParser()
# This flag is for internal use only; it assumes you have access to a headword list
# formatted as a dictionary whose keys are imported if this option is used; this
# requires for each item value to be a tuple whose third value matches 'entry' below.
argparser.add_argument('--id', action='store_true')
args = argparser.parse_args()
if args.id == True:
    use_lemma_id = True
    print("Loading DOE headword data...")
    # Set path to headword list here if available:
    doe_headwords_json = 'doeheadwords.json'
    with open(doe_headwords_json) as json_data:
        doe_headwords = json.load(json_data)
else:
    use_lemma_id = False

# A list of modern forms with OE headwords with which they overlap,
# generated by find_mne_forms.py on the basis of the output of
# attsp.sh (now superseded by the present script).
with open('pde.json') as json_data:
    pde = json.load(json_data)

html_folder = Path.cwd() / 'doe'
target_folder = Path.cwd() / 'attsp'
target_folder.mkdir(exist_ok=True)

# Substrings to be elided wherever they occur:
# (We cannot let the PDE list do all the cutting, also because this xrefers to other OE forms and lemmas.)
cuts = [
        '*gemagian)',
        'There are occurrences of forms of anbidian with on- for an- : ',
        'see onbīdan, and cf. PsGlL 68.7 onbidað), but perhaps for onbidiaþ (cf. PsGlI anbidiaþ, PsGlGHK anbidiað, PsGlD anbidigað, PsGlF andbidiað).',
        '*onbīcnian',
        'frio sconiosta',
        'gnēaþ / gnēad',
        'for hohful with second element evidently associated with fullfremed',
        '(or perh. take as an instance of a wk. 1 vb. *blendan ‘to mix’)',
        '(with u [?] over wynn, acc.sg.)',
        '*geblendan',
        'st. 7 vb. geblandan',
        '(for hand swa, BenR)',
        '(the MS character ⁊).',
        '(? for awille; or perh. for awillendlice or awillice; or if ā- is for ān-, perh. take as a form of ānwillendlīce [q.v.] or ānwillīce [q.v.])',
        ' (with first a and i added afterwards, ? for ageanhwirfte; or perh. ageanhwirfe, ageanhwirfenysse)',
        'efenheortnes',
        'with helle as gen.sg. of hell',
        'hiwlæs with a second læs written immediately below the first',
        'gnēað and gnȳðe',
        'forms of hēan adj',
        'forms of hēahnes',
        'to gehealdenne = custodiendus with an adj. like deriendlic',
        'abbreviations for hlīsbǣre',
        'and hlīsig',
        'dat.pl. heom',
        'the verb hȳrigan',
        'se gifra helle',
        'ðam deopan helle',
        'with brem repeated',
        'with traces of cm',
        'familias',
        'gloss for fyðerfōte',
        'as if f., cl. 2 or n. noun * gydde ?',
        'for grimman mannes',
        'forms of earnung',
        'bedupe. Forms with -pt-',
        'taken s.v. bedyppan',
        'Gen.pl. flana and dat.pl. flanum have been treated s.v. flān',
        'see cwene',
        'see scǣ',
        'With merging of æl',
        'the combining form of eall',
        'cf. gringwræce s.v. cringan',
        'mid mycele ferde',
        'tmesis',
        'umlaut',
        'ðone onsione',
        'hæ nū',
        'ðis hælo',
        ',',
        ':',
        ';',
        '·',
        '=',
        '|',
        '(',
        ')',
        '[',
        ']',
        '*',
        '‘',
        '’',
#        '/',
        '\\'
]

# Replacement rules:
regex = [
        (r'(heahlice) readings in Godric MSS GHIKL could alternatively be read as forms of the adj. hālig q.v.', r'\1'),
        (r'(halali) readings in Godric MSS GHIKL could alternatively be read as forms of the adj. hālig q.v.', r'\1'),
        (r'In late OE some forms of onbīdan with prefix.*$', ''),
        (r'^Anom\. form: ᚹ.*$', ''),
        (r'firgingatā \(\? -ā for -ena, \? -ā for -am\), ', 'firgingatā firgingatena firgingatam'),
        (r'(afursed)\. -eo- spellings occur in Psalters FGK', r'\1'),
        (r'awifte \(with w for p\)', 'awifte apifte'),
        (r' \(both for dat\.sg\. (ametenum)\)', r'\1'),
        (r'hweoga \(with g for þ.*\)', 'hweoga hweoþa'),
        (r'confusion with ǣghwæðer.*$', ''),
        (r'(heg) or an unusual spelling of ēac', r'\1'),
        (r'ða (bydel)', r'\1'),
        (r'brim faro. ðæs', 'brimfaro'),
        (r'(bradeleaces). Final e in composition is unique to this compound of brad', r'\1'),
        (r'bituinf letnise', 'bituinfletnise'),
        (r'the word has been read as (betothecd)', r'\1'),
        (r'brondas ðencan', ''),
        (r'\(cipher for ([^,]*), [^)]*\)', r'\1'),
        (r'(geembehte) ðu', r'\1'),
        (r'(ƀ(scop)?) ChronF\)', r'\1'),
        (r'((ge)?anlich?ie) we', r'\1'),
        (r'(nage) we', r'\1'),
        (r'(agefe) ue', r'\1'),
        (r'ðone (eage)', r'\1'),
        (r'ᚪ ᛚ ᛗ ᛖ ᛇ ᛏ ᛏ ᛁ ᚷ', 'ᚪᛚᛗᛖᛇᛏᛏᛁᚷ'),
        (r'·(ᛖ) ·(ᚹ) ·(ᚢ)·', r'\1\2\3'),
        (r'(ᚷᚫᚱᚩᚻᛁ) = (GÆROHI)', r'\1 gærohi'),
        (r'menn cyni', 'menncyni'),
        (r'(aldor) \.\.\. (sacerdæs)', r'\1\2'),
        (r'(aldor) \.\.\. (sacerda)', r'\1\2'),
        (r'(efne) \.\.\.(acunn)', r'\1\2 \2'),
        (r'(alduras) (sacerdas)', r'\1\2'),
        (r'(dagae) note that endingless forms are also common', r'\1'),
        (r'gedæled edlice', 'gedælededlice'),
        (r'mid cwealmlicre (flihte)', r'\1'),
        (r'se (ansine)', r'\1'),
        (r'Standard Paradigm (deoflu)', r'\1'),
        (r'Jun. Transcr. 71 (ægewriteras)', r'\1'),
        (r'presumably\ for\ (onbidað)', r'\1'),
        (r'but\ perhaps\ for\ (onbidiað)', r'\1'),
        (r'(egewritteras) and scepttenras have been suggested as possible readings', r'\1'),
        (r'(onbidedon).\ The\ form\ (onbiduð)\ glosses\ expectant\ in\ PsGlE\ 68\.7', r'\1 \2'),
        (r'm.pl. (deoflas) in Aldred', r'\1'),
        (r'(afyrsað). -eo- spellings occur in Psalters FGK', r'\1'),
        (r'(ædeawado). Past tense forms perhaps show influence of wk. 2 on wk. 1', r'\1'),
        (r'The spelling ǣrendwreca is etymological.*explanation, narrative’', ''),
        (r'a (æsnungdrenceas)', r'\1'),
        (r'wesan (draegtre)', r'\1'),
        (r'mid ðysse (hrægle)', r'\1'),
        (r'(eardungstowe) ðinum', r'\1'),
        (r'(earlippricco) \.\.\.\ ðio', r'\1'),
        (r'ða (earelipprica)', r'\1'),
        (r'(earliprica) ðæt', r'\1'),
        (r'\(for ([^,]*), [^)]*\)', r'\1'),
        (r'\(prob\. for ([^,]*), [^)]*\)', r'\1'),
        (r'\(\?? ?miswritten for ([^,]*), [^)]*\)', r'\1'),
        (r'\(\?? ?in error for ([^,]*), [^)]*\)', r'\1'),
        (r'\(= ([^,]*) for ([^,]*), [^)]*\)', r'\1 \2'),
        (r'\([^)]{0,20}\? for ([^,]*), [^)]*\)', r'\1'),
        (r' \([A-ZÆÞÐĘa-zæþðęāǣēīōūȳĀǢĒĪŌŪȲ0-9., ]+\)', ''),
        (r'b[ei]o ge', ''),
        (r'(derb) s', r'\1'),
        (r'Abbrev\. form\.(xv)\.(an)', r'\1\2'),
        (r'Abbrev\. forms\.(v)\.(tiene)', r'\1\2'),
        (r'Corrupt forms of (nraef)', r'\1'),
        (r'nænne (færeld)', r'\1'),
        (r'ælcne (færeld)', r'\1'),
        (r'y\.tiene \|*\.xv\.na', 'ytiene xvna'),
        (r'(forspebienne) for (forswebienne)', r'\1 \2'),
        (r'North\. (geheras)', r'\1'),
        (r'ða (heane)', r'\1'),
        (r'ðæt (færelt)', r'\1'),
        (r'ðet (foster)', r'\1'),
        (r'te (hernise)', r'\1'),
        (r'ðæt mycele (gylp)', r'\1'),
        (r'ðæt (geagl)', r'\1'),
        (r'(godene) or (godere)', r'\1 \2'),
        (r'se (fyrstmearce)', r'\1'),
        (r'se (druncnesse)', r'\1'),
        (r'(in) (sið) (gryre)', r'\1\2\3'),
        (r'mid mycclum (fyrde)', r'\1'),
        (r'ðio (earliprece) ðone', r'\1'),
        (r'(fore) (fengnisse)', r'\1\2'),
        (r'(græi) (an)', r'\1\2'),
        (r'(forcyððed) \(MSol', r'\1'),
        (r'(forbinde) ge', r'\1'),
        (r'(folce) (getrume)', r'\1\2'),
        (r'(huru) (fæðmum)', r'\1\2'),
        (r'(imbrae) (rae)', r'\1\2'),
        (r'(hea) (an)', r'\1\2'),
        (r'(earlipprica) \.\.\. ðio', r'\1'),
        (r'ðone (ęarliprica)', r'\1'),
        (r'(eolhxsecg) Hickes transcr\. (eolhx) (secc)', r'\1 \2\3'),
        (r'(galpania) ⁊ anan', r'\1'),
        (r'\.\.\. (gefleanne)', r'\1'),
        (r'(efne) \.\.\.(gesette)', r'\1\2'),
        (r'(efne) \.\.\.(geworhte)', r'\1\2'),
        (r'(eft) \.\.\.(\w+)', r'\1\2 \2'),
        (r'(fe) \.\.\.(cuoeð)', r'\1\2'),
        (r'(frendles) \.\.\. (ne)', r'\1 \1\2'),
        (r'(for[ðþ]) \.\.\.(\w+)', r'\1\2'),
        (r'(for) \.\.\.(\w+)', r'\1\2'),
        (r'f\.(hracan)', r'\1'),
        (r'(ge) \.\.\.(\w+)', r'\1\2'),
        (r'(fore) \.\.\.(\w+)', r'\1\2'),
        (r'(fram) \.\.\.(\w+)', r'\1\2'),
        (r'(from) \.\.\.(\w+)', r'\1\2'),
        (r'(fyrn) \.\.\.(\w+)', r'\1\2'),
        (r'(fe) \.\.\.(\w+)', r'\1\2'),
        (r'(heh) \.\.\.(\w+)', r'\1\2'),
        (r'(huelc) \.\.\. (iueres)', r'\1\2'),
        (r'(eft) (to) (\w*nne)', r'\3 \1\2'),
        (r'(yrðe) yrðe', r'\1'),
        (r'(geafæn) \.\.\.(læce)', r'\1\2'),
        (r'(behydda) \.\.\. (dedre)', r'\1\2'),
        (r'(cul) (bod) (gehnades) with\ ł\ cum\ bel\ written\ above\ cul\ bod\ in\ a\ later\ hand', r'\1\2\3'),
        (r'fr (fræge)', r'\1'),
        (r'PsGl[A-N]+', ''),
        (r'se (burhwaru)', r'\1'),
        (r'(forgife) ge', r'\1'),
        (r'(freo) (don)', r'\1\2'),
        (r'se (fyrd)', r'\1'),
        (r'(forweorpe) i', r'\1'),
        (r'te (fullfremmanne)', r'\1'),
        (r'(faere) ue', r'\1'),
        (r'ðæt\ \.\.\.\ feord', ''),
        (r'ðæt (ferd)', r'\1'),
        (r'w (feounge)', r'\1'),
        (r'(foresce) (g)', r'/\1\2'),
        (r'te (habbe)', r'\1'),
        (r'(forewit) (tiendlicer)', r'\1\2'),
        (r'(hen) se', r'\1'),
        (r'þet (foster)', r'\1'),
        (r'(an) (twig)', r'\1\2')
]

# Sequences to be replaced by a space wherever thy occur:
spaces = [
        ' ||| ',
        ' || ',
        ' | ',
        ', '
        '; ',
        ' or '
]

def extract():
    entries = dict()
    inverted = dict()
    for entry in html_folder.glob('*.html'):
        ref = entry.name[:-5]
        print(ref)
        if use_lemma_id == True:
            lemma_id = next((k for k,v in doe_headwords.items() if v[2] == ref), None)
        with open(entry) as html_file:
            soup = BeautifulSoup(html_file, 'html.parser')
    
        lemma_node = soup.find('div', class_=['doe-hd', 'doe-sub', 'doe-affix'])
        lemma = lemma_node.get_text().strip('\n')
        pos_node = soup.find('div', class_=['doe-pos'])
        if pos_node is None:
            pos = ''
        else:
            pos = pos_node.get_text()
        occ_node = soup.find('div', class_=['doe-occ'])
        if occ_node is None:
            occ = ''
        else:
            occ = occ_node.get_text()
        spelling_strings = [i.get_text().rstrip('.') for i in soup.select('div[class^="doe-attsp"]')]
        spellings = []
        for line in spelling_strings:
            for pattern in spaces:
                line = line.replace(pattern, ' ')
            for pattern,replacement in regex:
                line = re.sub(pattern, replacement, line)
            for pattern in cuts:
                line = line.replace(pattern, '')
            spellings.extend(line.split())
        spellings = list(set(spellings))
        purged_spellings = sorted(list(set([form for form in spellings 
                            if not (form in pde and not lemma in pde[form])
                            and re.search("^[a-zþæðęłœøƀāēīōūȳ\u16A0-\u16FF]+$", form)
                            ])))
    
        entry_dict = {}
        if use_lemma_id:
            entry_dict['id'] = lemma_id
        entry_dict['lemma'] = lemma
        entry_dict['pos'] = pos
        entry_dict['freq'] = occ
        entry_dict['attsp'] = purged_spellings
        entries[ref] = entry_dict
        for spelling in purged_spellings:
            if not spelling in inverted:
                inverted[spelling] = []
            if not ref in inverted[spelling]:
                inverted[spelling].append((ref, lemma, pos, occ))
            inverted[spelling] = sorted(inverted[spelling], key=lambda x: x[3], reverse=True)
    inverted = dict(sorted(inverted.items()))
    entries = dict(sorted(entries.items()))
    
    with open('attsp.json', 'w', encoding='utf-8') as output:
        json.dump(entries, output, ensure_ascii=False, indent=4)
    
    with open('attsp_inverted.json', 'w') as outfile:
        json.dump(inverted, outfile)
    
    for k,v in entries.items():
        filename = k + '.txt'
        outfile = Path.cwd() / 'attsp' / filename
        if outfile.is_file():
            outfile.unlink()
        with open(outfile, 'w') as f:
            f.write('# ' + v['lemma'] + '\n')
            f.write('# ' + v['pos'] + '\n')
            f.write('# ' + v['freq'])
            for i in v['attsp']:
                f.write(f'\n{i}')

if __name__ == '__main__':
    extract()
