# This script will replace attsp.sh
# but is as yet under development.
# Copyright Paul Langeslag 2026
import json,re
from pathlib import Path
from bs4 import BeautifulSoup

html_folder = Path.cwd() / 'doe'
target_folder = Path.cwd() / 'attsp'
target_folder.mkdir(exist_ok=True)

cuts = [
        'Forms originally proper to the dative are used for the general object case in some texts of s. xii and later',
        'The form may alternatively be taken as two words with helle as gen.sg. of hell',
        'hiwlæs with a second læs written immediately below the first',
        'Forms of the interrogative particle with -e',
        'these forms may represent scribal compromise between gnēað and gnȳðe',
        'These instances may alternatively be taken as forms of hēan adj',
        'With - es as a generalized adverbial marker',
        'these forms may alternatively be read as merographs of forms of hēahnes',
        'form may have arisen by confusion of the dat.inf. to gehealdenne = custodiendus with an adj. like deriendlic',
        'heahlice readings in Godric MSS GHIKL could alternatively be read as forms of the adj. hālig q.v.',
        'I. Active forms and past part',
        'II. Passive forms excluding the past part',
        'adjectival inflectional endings are added to gen.sg.',
        'and dat.pl. forms. Genitives formed in this way generally decline as possessive adjectives',
        'and case. The motivation behind doubly inflected dative pl. forms is unclear',
        'but these may have been invented in order to disambiguate dat.pl. heom',
        'agreeing with the modified noun in number',
        'A. Forms derived from the Germanic pres.pass. inflection',
        'used as both pres. and pret. pass.',
        'these forms could also be taken as abbreviations for hlīsbǣre',
        'and hlīsig',
        'adjectival inflectional endings are added to gen.sg.',
        'and dat.pl. forms. Genitives formed in this way generally decline as possessive adjectives',
        'agreeing with the modified noun in number',
        'and case. The motivation behind doubly inflected dative pl. forms is unclear',
        'but these may have been invented in order to disambiguate dat.pl. heom from the identically spelled m./n.dat.sg. form. The attested forms are as follows',
        'Gen.pl. with m./n.dat.sg. or dat.pl. inflection',
        'For forms of the f.nom.sg. 3rd pers. pronoun beginning in sc',
        'perhaps written through confusion with forms of',
        'The hyrig- spellings may be formed from the root of the verb hȳrigan',
        'or may represent corrupt forms of hȳringmann2',
        'se gifra helle',
        'ðam deopan helle',
        'with traces of cm written above the line',
        'Uninfl. North. glosses of familias',
        'Gen.pl. with m./n.dat.sg. or dat.pl. inflection',
        'these forms have alternatively been taken as n.',
        'Dat.pl. with dat.pl. inflection',
        'Att. sp.: ',
        'Compar.: ',
        'Late: ',
        'Rarely',
        'Abbrev. form in a gloss',
        'Abbrev. forms in glosses: ',
        'Anom. forms',
        'Anom. form in a gloss',
        'Corrupt form in a gloss: ',
        'Corrupt forms in late MS',
        'In North. glosses',
        'Unambig. f. wk.',
        'As alternative gloss for fyðerfōte',
        'Strong Adjective:',
        'Weak Adjective',
        'With st. inflections',
        'Northumbrian paradigm',
        'Forms without final n',
        'Unambiguous wk. 2 forms',
        'as if f., cl. 2 or n. noun * gydde ?',
        'Endingless in acc.sg.',
        'Spellings in eg- are mainly North',
        'Spellings in oe- are North',
        'Spellings in æu- are from ChronE additions',
        'Spellings in oef- are from Li',
        'Spellings in efeg- are from CP MS Camb.Trin. R.5.22',
        'Spellings with initial h are from CP MS CUL Ii.ii.4',
        'Forms in oe- are from DurRit',
        'Forms with -n- are Northumbrian',
        'Some spellings in gearn- may alternatively represent forms of earnung with initial g',
        'The manuscript is damaged and difficult to read',
        'The attestations are ambiguous and may be interpreted as forms of the adjective',
        'excluding all forms found also with other dialect groupings',
        'but the last letter is doubtful',
        'Spellings with -z- are found in MSS of s. x med. and later',
        'bedupe. Forms with -pt-',
        'pð could also be taken s.v. bedyppan',
        'in a number of citations confusion is attested in the variants',
        'Some forms in gearn- / georn- may alternatively be taken as forms of earnian with initial g',
        'Form in geard- may alternatively be taken as eard- with initial g',
        'Gen.pl. flana and dat.pl. flanum have been treated s.v. flān',
        'and treated as OE copied by foreign scribes',
        'For unambiguously weak forms',
        'occas. in s.xii MSS',
        'see cwene',
        'see scǣ',
        'With metathesis',
        'With unmetathesized suffix',
        'With inflected first element',
        'With merging of æl',
        'followed by first minim of u',
        '-ei- spellings are Northumbrian',
        'confessor may be either OE or Lat',
        'Forms with medial n predominate in Ælfric',
        'Spellings in eæll- are mainly in PsGlE',
        'Spellings in eærm(- are from PsCaE',
        'Spellings in æl-',
        'the combining form of eall',
        'for other gr- spellings',
        'With ǣ-',
        'cf. gringwræce s.v. cringan',
        'Bede MSS BCaO',
        'Masculine',
        'Neuter',
        'Feminine',
        'wk.gen.pl.',
        'nom.sg.',
        'acc.sg. - ',
        'gen.sg. - ',
        'gen.sg. ',
        'dat.sg. - ',
        'dat.sg. ',
        'nom./acc.sg.',
        'nom./acc.pl.',
        'both acc.pl.',
        'nom.pl.',
        'acc.pl.',
        'gen.pl.',
        'dat.pl.',
        'pret.sg.',
        'M. wk. with t',
        'gender',
        'With contr.',
        'Forms with -dd-',
        'Forms in LdGl',
        'Forms in -nd-',
        'Fragm. forms',
        'CollGl 32.3',
        'CollGl 38.6 are preserved in continental MSS',
        'CollGl',
        'HomU 32 MS B',
        'With -swæc',
        'With -spæc',
        'Redupl. pret.',
        'ðone onsione',
        'hæ nū',
        'ðis hælo',
        'expanded as ',
        'm. more common',
        'IE bheu-',
        'IE wes-',
        'IE es-',
        'PGerm. ar-',
        'M. cl. 3 (pl.)',
        'Wk. m ',
        'Wk. 1',
        'St. pl.',
        'In sg.',
        'with -m',
        'cl. 3',
        'cl. 4',
        '2nd sg',
        'wk.',
        'Wk.',
        'St.',
        'st.',
        'PPs [prose]',
        'M. or N.',
        'M.',
        'N.',
        'F.',
        'm./f./n.',
        'm./n.dat.sg.',
        'Ru1',
        'Corrupt',
        'With',
        'xii/xiii',
        'xii-xiii',
        'xiii',
        'xii',
        ',',
        ':',
        ';',
        '=',
        '|',
        '(',
        ')',
        '[',
        ']',
        '*'
]

regex = [
        (r'In late OE some forms of onbīdan with prefix.*$', ''),
        (r'^Anom\. form: ᚹ.*$', ''),
        (r'firgingatā \(\? -ā for -ena, \? -ā for -am\), ', 'firgingatā firgingatena firgingatam'),
        (r'(afursed)\. -eo- spellings occur in Psalters FGK', r'\1'),
        (r'awifte \(with w for p\)', 'awifte apifte'),
        (r' \(both for dat\.sg\. (ametenum)\)', r'\1'),
        (r'hweoga \(with g for þ.*\)', 'hweoga hweoþa'),
        (r'confusion with ǣghwæðer.*$', ''),
        (r'ða (bydel)', r'\1'),
        (r'brim faro. ðæs', 'brimfaro'),
        (r'(bradeleaces). Final e in composition is unique to this compound of brad', r'\1'),
        (r'bituinf letnise', 'bituinfletnise'),
        (r'the word has been read as (betothecd)', r'\1'),
        (r'brondas ðencan', ''),
        (r'For forms of the f.nom.sg. 3rd pers. pronoun beginning in sc$', ''),
        (r'\(cipher for ([^,]*), [^)]*\)', r'\1'),
        (r'(geembehte) ðu', r'\1'),
        (r'(ƀ(scop)?) ChronF\)', r'\1'),
        (r'((ge)?anlich?ie) we', r'\1'),
        (r'(nage) we', r'\1'),
        (r'(agefe) ue', r'\1'),
        (r'ðone (eage)', r'\1'),
        (r'ᚪ ᛚ ᛗ ᛖ ᛇ ᛏ ᛏ ᛁ ᚷ', 'ᚪᛚᛗᛖᛇᛏᛏᛁᚷ'),
        (r'·(ᛖ) ·(ᚹ) ·(ᚢ)·', r'\1\2\3'),
        (r'(ᚠᚩᛚᚳ) = (folc)', r'\1 \2'),
        (r'(ᚷᚫᚱᚩᚻᛁ) = (GÆROHI)', r'\1 gærohi'),
        (r'menn cyni', 'menncyni'),
        (r'(aldor) \.\.\. (sacerdæs)', r'\1\2'),
        (r'(aldor) \.\.\. (sacerda)', r'\1\2'),
        (r'(efne) \.\.\.(acunn)', r'\1\2 \2'),
        (r'(alduras) (sacerdas)', r'\1\2'),
        (r'(dagae) note that endingless forms are also common', r'\1'),
        (r'gedæled edlice', 'gedælededlice'),
        (r'mid cwealmlicre (flihte)', r'\1'),
        (r'se (ansine)', r'\1'),
        (r'Standard Paradigm (deoflu)', r'\1'),
        (r'Jun. Transcr. 71 (ægewriteras)', r'\1'),
        (r'presumably\ for\ (onbidað)', r'\1'),
        (r'but\ perhaps\ for\ (onbidiað)', r'\1'),
        (r'(egewritteras) and scepttenras have been suggested as possible readings', r'\1'),
        (r'(onbidedon).\ The\ form\ (onbiduð)\ glosses\ expectant\ in\ PsGlE\ 68\.7', r'\1 \2'),
        (r'm.pl. (deoflas) in Aldred', r'\1'),
        (r'(afyrsað). -eo- spellings occur in Psalters FGK', r'\1'),
        (r'(ædeawado). Past tense forms perhaps show influence of wk. 2 on wk. 1', r'\1'),
        (r'The spelling ǣrendwreca is etymological.*explanation, narrative’', ''),
        (r'a (æsnungdrenceas)', r'\1'),
        (r'wesan (draegtre)', r'\1'),
        (r'mid ðysse (hrægle)', r'\1'),
        (r'\(for ([^,]*), [^)]*\)', r'\1'),
        (r'\(prob\. for ([^,]*), [^)]*\)', r'\1'),
        (r'\(\?? ?miswritten for ([^,]*), [^)]*\)', r'\1'),
        (r'\(\?? ?in error for ([^,]*), [^)]*\)', r'\1'),
        (r'\(= ([^,]*) for ([^,]*), [^)]*\)', r'\1 \2'),
        (r'\([^)]{0,20}\? for ([^,]*), [^)]*\)', r'\1'),
        (r' \([A-ZÆÞÐĘa-zæþðęāǣēīōūȳĀǢĒĪŌŪȲ0-9., ]+\)', ''),
        (r'b[ei]o ge', ''),
        (r'(derb) s', r'\1'),
        (r'Abbrev\. form\.(xv)\.(an)', r'\1\2'),
        (r'Abbrev\. forms\.(v)\.(tiene)', r'\1\2'),
        (r'Corrupt forms of (nraef)', r'\1'),
        (r'nænne (færeld)', r'\1'),
        (r'North\. (geheras)', r'\1'),
        (r'ða (heane)', r'\1'),
        (r'ðæt (færelt)', r'\1'),
        (r'ðet (foster)', r'\1'),
        (r'te (hernise)', r'\1'),
        (r'ðæt mycele (gylp)', r'\1'),
        (r'ðæt (geagl)', r'\1'),
        (r'(godene) or (godere)', r'\1 \2'),
        (r'(gydde) as if f\.', r'\1'),
        (r'se (fyrstmearce)', r'\1'),
        (r'se (druncnesse)', r'\1'),
        (r'(in) (sið) (gryre)', r'\1\2\3'),
        (r'mid mycclum (fyrde)', r'\1'),
        (r'ðio (earliprece) ðone', r'\1'),
        (r'(fore) (fengnisse)', r'\1\2'),
        (r'(græi) (an)', r'\1\2'),
        (r'(forcyððed) \(MSol', r'\1'),
        (r'(forbinde) ge', r'\1'),
        (r'(folce) (getrume)', r'\1\2'),
        (r'(huru) (fæðmum)', r'\1\2'),
        (r'(imbrae) (rae)', r'\1\2'),
        (r'(hea) (an)', r'\1\2'),
        (r'(earlipprica) \.\.\. ðio', r'\1'),
        (r'ðone (ęarliprica)', r'\1'),
        (r'(eolhxsecg) Hickes transcr\. (eolhx) (secc)', r'\1 \2\3'),
        (r'(galpania) ⁊ anan', r'\1'),
        (r'(efne) \.\.\.(gesette)', r'\1\2'),
        (r'(efne) \.\.\.(geworhte)', r'\1\2'),
        (r'(eft) \.\.\.(\w+)', r'\1\2 \2'),
        (r'(for[ðþ]) \.\.\.(\w+)', r'\1\2'),
        (r'(for) \.\.\.(\w+)', r'\1\2'),
        (r'(fore) \.\.\.(\w+)', r'\1\2'),
        (r'(from) \.\.\.(\w+)', r'\1\2'),
        (r'(fyrn) \.\.\.(\w+)', r'\1\2'),
        (r'(fe) \.\.\.(\w+)', r'\1\2'),
        (r'(heh) \.\.\.(\w+)', r'\1\2'),
        (r'(geafæn) \.\.\.(læce)', r'\1\2'),
        (r'fr (fræge)', r'\1'),
        (r'se (burhwaru)', r'\1'),
        (r'(forgife) ge', r'\1'),
        (r'(freo) (don)', r'\1\2'),
        (r'se (fyrd)', r'\1'),
        (r'ðæt (ferd)', r'\1'),
        (r'w (feounge)', r'\1'),
        (r'(foresce) (g)', r'/\1\2'),
        (r'(forewit) (tiendlicer)', r'\1\2'),
        (r'(hen) se', r'\1')
]

spaces = [
        ' ||| ',
        ' || ',
        ' | ',
        ', '
        '; ',
        ' or '
]

mne_forms = [
        'with',
        'corrupt',
        'to',
        'f.',
        'we',
        'Att.sp.',
        'Fragm.',
        'pres.subj.pl.',
        'Abbrev.',
        'LambHom',
        'Morris',
        'glossing',
        'gloss',
        'by',
        'PsGlG',
        'Anom.',
        'm./f./n.',
        'm./n.dat.sg.',
        'n.',
        'in-',
        'on-',
        'y'
]

entries = dict()
for entry in html_folder.glob('*.html'):
    ref = entry.name[:-5]
    print(ref)
    with open(entry) as html_file:
        soup = BeautifulSoup(html_file, 'html.parser')

    lemma_node = soup.find('div', class_=['doe-hd', 'doe-sub', 'doe-affix'])
    lemma = lemma_node.get_text().strip('\n')
    pos_node = soup.find('div', class_=['doe-pos'])
    if pos_node is None:
        pos = ''
    else:
        pos = pos_node.get_text()
    occ_node = soup.find('div', class_=['doe-occ'])
    if occ_node is None:
        occ = ''
    else:
        occ = occ_node.get_text()
    spelling_strings = [i.get_text().rstrip('.') for i in soup.select('div[class^="doe-attsp"]')]
    spellings = []
    for line in spelling_strings:
        for pattern in spaces:
            line = line.replace(pattern, ' ')
        for pattern,replacement in regex:
            line = re.sub(pattern, replacement, line)
        for pattern in cuts:
            line = line.replace(pattern, '')
        spellings.extend(line.split())
    spellings = sorted(list(set(spellings)))
    purged_spellings = [form for form in spellings if form not in mne_forms and not re.search('^[0-9]*$', form)]

    entry_dict = {
            'lemma': lemma,
            'pos': pos,
            'freq': occ,
            'attsp': purged_spellings
            }
    entries[ref] = entry_dict

with open('attsp.json', 'w', encoding='utf-8') as output:
    json.dump(entries, output, ensure_ascii=False, indent=4)
